FROM node:18-alpine

# Install FFmpeg
RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN echo "Forcing cache invalidation" && npx nest build

EXPOSE 3000

CMD ["node", "dist/main.js"]
# [GW] Last check at Fri Jan  9 06:14:24 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:15:45 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:16:05 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:16:25 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:16:35 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:17:05 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:17:35 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:17:55 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:19:26 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:19:56 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:21:06 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:23:17 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:24:07 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:26:48 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:27:08 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:27:18 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:27:58 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:28:59 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:31:19 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:31:39 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:32:39 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:33:20 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:35:00 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:36:30 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:37:11 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:37:31 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:38:21 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:39:02 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:40:12 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:40:32 PM UTC 2026
# [GW] Last check at Fri Jan  9 06:40:42 PM UTC 2026
